// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: quantumchain/problems/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryListProblemsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListProblemsRequest) Reset()         { *m = QueryListProblemsRequest{} }
func (m *QueryListProblemsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListProblemsRequest) ProtoMessage()    {}
func (*QueryListProblemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{2}
}
func (m *QueryListProblemsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListProblemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListProblemsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListProblemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListProblemsRequest.Merge(m, src)
}
func (m *QueryListProblemsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListProblemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListProblemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListProblemsRequest proto.InternalMessageInfo

func (m *QueryListProblemsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryListProblemsResponse struct {
	Problems   []Problem           `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryListProblemsResponse) Reset()         { *m = QueryListProblemsResponse{} }
func (m *QueryListProblemsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListProblemsResponse) ProtoMessage()    {}
func (*QueryListProblemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{3}
}
func (m *QueryListProblemsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListProblemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListProblemsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListProblemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListProblemsResponse.Merge(m, src)
}
func (m *QueryListProblemsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListProblemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListProblemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListProblemsResponse proto.InternalMessageInfo

func (m *QueryListProblemsResponse) GetProblems() []Problem {
	if m != nil {
		return m.Problems
	}
	return nil
}

func (m *QueryListProblemsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetProblemRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetProblemRequest) Reset()         { *m = QueryGetProblemRequest{} }
func (m *QueryGetProblemRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetProblemRequest) ProtoMessage()    {}
func (*QueryGetProblemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{4}
}
func (m *QueryGetProblemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProblemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProblemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProblemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProblemRequest.Merge(m, src)
}
func (m *QueryGetProblemRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProblemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProblemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProblemRequest proto.InternalMessageInfo

func (m *QueryGetProblemRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetProblemResponse struct {
	Problem Problem `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem"`
}

func (m *QueryGetProblemResponse) Reset()         { *m = QueryGetProblemResponse{} }
func (m *QueryGetProblemResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetProblemResponse) ProtoMessage()    {}
func (*QueryGetProblemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{5}
}
func (m *QueryGetProblemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProblemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProblemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProblemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProblemResponse.Merge(m, src)
}
func (m *QueryGetProblemResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProblemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProblemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProblemResponse proto.InternalMessageInfo

func (m *QueryGetProblemResponse) GetProblem() Problem {
	if m != nil {
		return m.Problem
	}
	return Problem{}
}

type QueryGetProblemByNameRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryGetProblemByNameRequest) Reset()         { *m = QueryGetProblemByNameRequest{} }
func (m *QueryGetProblemByNameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetProblemByNameRequest) ProtoMessage()    {}
func (*QueryGetProblemByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{6}
}
func (m *QueryGetProblemByNameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProblemByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProblemByNameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProblemByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProblemByNameRequest.Merge(m, src)
}
func (m *QueryGetProblemByNameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProblemByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProblemByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProblemByNameRequest proto.InternalMessageInfo

func (m *QueryGetProblemByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryGetProblemByNameResponse struct {
	Problem Problem `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem"`
}

func (m *QueryGetProblemByNameResponse) Reset()         { *m = QueryGetProblemByNameResponse{} }
func (m *QueryGetProblemByNameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetProblemByNameResponse) ProtoMessage()    {}
func (*QueryGetProblemByNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e27a575b8ed53188, []int{7}
}
func (m *QueryGetProblemByNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProblemByNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProblemByNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProblemByNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProblemByNameResponse.Merge(m, src)
}
func (m *QueryGetProblemByNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProblemByNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProblemByNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProblemByNameResponse proto.InternalMessageInfo

func (m *QueryGetProblemByNameResponse) GetProblem() Problem {
	if m != nil {
		return m.Problem
	}
	return Problem{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "quantumchain.problems.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "quantumchain.problems.v1.QueryParamsResponse")
	proto.RegisterType((*QueryListProblemsRequest)(nil), "quantumchain.problems.v1.QueryListProblemsRequest")
	proto.RegisterType((*QueryListProblemsResponse)(nil), "quantumchain.problems.v1.QueryListProblemsResponse")
	proto.RegisterType((*QueryGetProblemRequest)(nil), "quantumchain.problems.v1.QueryGetProblemRequest")
	proto.RegisterType((*QueryGetProblemResponse)(nil), "quantumchain.problems.v1.QueryGetProblemResponse")
	proto.RegisterType((*QueryGetProblemByNameRequest)(nil), "quantumchain.problems.v1.QueryGetProblemByNameRequest")
	proto.RegisterType((*QueryGetProblemByNameResponse)(nil), "quantumchain.problems.v1.QueryGetProblemByNameResponse")
}

func init() {
	proto.RegisterFile("quantumchain/problems/v1/query.proto", fileDescriptor_e27a575b8ed53188)
}

var fileDescriptor_e27a575b8ed53188 = []byte{
	// 594 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x51, 0x6b, 0xd3, 0x50,
	0x14, 0xc7, 0x7b, 0x6b, 0x57, 0xdd, 0x99, 0x88, 0x5e, 0x87, 0xd6, 0x30, 0x63, 0x97, 0x39, 0xad,
	0xd5, 0xe5, 0xae, 0x99, 0xa8, 0xf8, 0x66, 0x05, 0xf7, 0x22, 0x52, 0xf3, 0x38, 0x84, 0x71, 0xb3,
	0x5e, 0x62, 0x60, 0xc9, 0x4d, 0x9b, 0xb4, 0x58, 0xc6, 0x5e, 0xfc, 0x04, 0x03, 0x3f, 0x82, 0x3e,
	0xb8, 0x37, 0xbf, 0x81, 0xaf, 0x7b, 0x1c, 0xf8, 0xe2, 0x93, 0x48, 0x2b, 0xf8, 0x35, 0x24, 0x37,
	0x37, 0x6b, 0xbb, 0x2e, 0x6b, 0x0a, 0xbe, 0x84, 0x4b, 0x72, 0xfe, 0xe7, 0xff, 0x3b, 0xff, 0x9c,
	0x04, 0xee, 0xb6, 0x3a, 0xd4, 0x0b, 0x3b, 0xee, 0xce, 0x7b, 0xea, 0x78, 0xc4, 0x6f, 0x73, 0x6b,
	0x97, 0xb9, 0x01, 0xe9, 0xd6, 0x48, 0xab, 0xc3, 0xda, 0x3d, 0xdd, 0x6f, 0xf3, 0x90, 0xe3, 0xd2,
	0x68, 0x95, 0x9e, 0x54, 0xe9, 0xdd, 0x9a, 0x72, 0x8d, 0xba, 0x8e, 0xc7, 0x89, 0xb8, 0xc6, 0xc5,
	0x4a, 0x75, 0x87, 0x07, 0x2e, 0x0f, 0x88, 0x45, 0x03, 0x16, 0x77, 0x21, 0xdd, 0x9a, 0xc5, 0x42,
	0x5a, 0x23, 0x3e, 0xb5, 0x1d, 0x8f, 0x86, 0x0e, 0xf7, 0x64, 0xed, 0xa2, 0xcd, 0x6d, 0x2e, 0x8e,
	0x24, 0x3a, 0xc9, 0xbb, 0x4b, 0x36, 0xe7, 0xf6, 0x2e, 0x23, 0xd4, 0x77, 0x08, 0xf5, 0x3c, 0x1e,
	0x0a, 0x49, 0x20, 0x9f, 0xae, 0xa6, 0x22, 0xfb, 0xb4, 0x4d, 0xdd, 0xa4, 0x2c, 0x7d, 0xb2, 0xb0,
	0xe7, 0x33, 0x59, 0xa5, 0x2d, 0x02, 0x7e, 0x1b, 0x21, 0x36, 0x84, 0xd4, 0x64, 0xad, 0x0e, 0x0b,
	0x42, 0x6d, 0x0b, 0xae, 0x8f, 0xdd, 0x0d, 0x7c, 0xee, 0x05, 0x0c, 0xbf, 0x84, 0x62, 0x6c, 0x51,
	0x42, 0x65, 0x54, 0x59, 0x30, 0xca, 0x7a, 0x5a, 0x2e, 0x7a, 0xac, 0xac, 0xcf, 0x1f, 0xfd, 0xba,
	0x93, 0xfb, 0xfa, 0xf7, 0x5b, 0x15, 0x99, 0x52, 0xaa, 0x59, 0x50, 0x12, 0xbd, 0x5f, 0x3b, 0x41,
	0xd8, 0x90, 0x0a, 0xe9, 0x8b, 0x5f, 0x01, 0x0c, 0x23, 0x92, 0x26, 0xf7, 0xf4, 0x38, 0x4f, 0x3d,
	0xca, 0x53, 0x8f, 0xdf, 0x8a, 0xcc, 0x53, 0x6f, 0x50, 0x9b, 0x49, 0xad, 0x39, 0xa2, 0xd4, 0x0e,
	0x11, 0xdc, 0x3a, 0xc3, 0xe4, 0x64, 0x8c, 0x4b, 0x09, 0x6a, 0x09, 0x95, 0x2f, 0x54, 0x16, 0x8c,
	0xe5, 0x73, 0x06, 0x89, 0xcf, 0xf5, 0x42, 0x34, 0x89, 0x79, 0x22, 0xc4, 0x9b, 0x63, 0xa8, 0x79,
	0x81, 0x7a, 0x7f, 0x2a, 0x6a, 0x4c, 0x30, 0xc6, 0x5a, 0x81, 0x1b, 0x02, 0x75, 0x93, 0x25, 0xa4,
	0x49, 0x1a, 0x57, 0x20, 0xef, 0x34, 0x45, 0x0a, 0x05, 0x33, 0xef, 0x34, 0xb5, 0x77, 0x70, 0x73,
	0xa2, 0x52, 0x8e, 0xf4, 0x02, 0x2e, 0x4a, 0x32, 0x99, 0x5a, 0xe6, 0x89, 0x12, 0x9d, 0x66, 0xc0,
	0xd2, 0xa9, 0xee, 0xf5, 0xde, 0x1b, 0xea, 0x26, 0xf9, 0x62, 0x0c, 0x05, 0x8f, 0xba, 0x4c, 0xf4,
	0x9f, 0x37, 0xc5, 0x59, 0xb3, 0xe0, 0x76, 0x8a, 0xe6, 0xbf, 0x71, 0x19, 0x87, 0x73, 0x30, 0x27,
	0x4c, 0xf0, 0x01, 0x82, 0x62, 0xbc, 0x57, 0xf8, 0x51, 0x7a, 0x9b, 0xc9, 0x75, 0x56, 0xd6, 0x32,
	0x56, 0xc7, 0xd0, 0xda, 0x83, 0x8f, 0x3f, 0xfe, 0x7c, 0xca, 0xaf, 0xe0, 0x65, 0x22, 0x65, 0x6b,
	0x69, 0x9f, 0x1a, 0xfe, 0x82, 0xe0, 0xf2, 0xe8, 0x8e, 0x61, 0x63, 0x8a, 0xd5, 0x19, 0x5b, 0xaf,
	0x6c, 0xcc, 0xa4, 0x91, 0x90, 0x0f, 0x05, 0xe4, 0x2a, 0x5e, 0x39, 0x0f, 0x32, 0xa1, 0xfa, 0x8c,
	0x00, 0x86, 0xef, 0x08, 0xaf, 0x4f, 0x31, 0x9c, 0x58, 0x45, 0xa5, 0x36, 0x83, 0x42, 0x02, 0xae,
	0x0b, 0xc0, 0x2a, 0xae, 0x64, 0x00, 0x24, 0x7b, 0x4e, 0x73, 0x1f, 0x7f, 0x47, 0x70, 0xf5, 0xf4,
	0x26, 0xe1, 0x27, 0x99, 0x9d, 0xc7, 0xd6, 0x55, 0x79, 0x3a, 0xb3, 0x4e, 0x72, 0x3f, 0x17, 0xdc,
	0x8f, 0xb1, 0x91, 0x81, 0x7b, 0xdb, 0xea, 0x6d, 0x47, 0x1f, 0x02, 0xd9, 0x8b, 0xae, 0xfb, 0xf5,
	0x67, 0x47, 0x7d, 0x15, 0x1d, 0xf7, 0x55, 0xf4, 0xbb, 0xaf, 0xa2, 0x83, 0x81, 0x9a, 0x3b, 0x1e,
	0xa8, 0xb9, 0x9f, 0x03, 0x35, 0xb7, 0xa5, 0x8e, 0x37, 0xfb, 0x30, 0x6c, 0x27, 0xfe, 0xc6, 0x56,
	0x51, 0xfc, 0x8e, 0x37, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x14, 0x26, 0xfa, 0x5e, 0x90, 0x06,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListProblems returns all registered problems, optionally paginated.
	ListProblems(ctx context.Context, in *QueryListProblemsRequest, opts ...grpc.CallOption) (*QueryListProblemsResponse, error)
	// GetProblem returns the problem with the given ID.
	GetProblem(ctx context.Context, in *QueryGetProblemRequest, opts ...grpc.CallOption) (*QueryGetProblemResponse, error)
	// GetProblemByName returns the problem registered under the given unique name.
	GetProblemByName(ctx context.Context, in *QueryGetProblemByNameRequest, opts ...grpc.CallOption) (*QueryGetProblemByNameResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/quantumchain.problems.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListProblems(ctx context.Context, in *QueryListProblemsRequest, opts ...grpc.CallOption) (*QueryListProblemsResponse, error) {
	out := new(QueryListProblemsResponse)
	err := c.cc.Invoke(ctx, "/quantumchain.problems.v1.Query/ListProblems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProblem(ctx context.Context, in *QueryGetProblemRequest, opts ...grpc.CallOption) (*QueryGetProblemResponse, error) {
	out := new(QueryGetProblemResponse)
	err := c.cc.Invoke(ctx, "/quantumchain.problems.v1.Query/GetProblem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProblemByName(ctx context.Context, in *QueryGetProblemByNameRequest, opts ...grpc.CallOption) (*QueryGetProblemByNameResponse, error) {
	out := new(QueryGetProblemByNameResponse)
	err := c.cc.Invoke(ctx, "/quantumchain.problems.v1.Query/GetProblemByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListProblems returns all registered problems, optionally paginated.
	ListProblems(context.Context, *QueryListProblemsRequest) (*QueryListProblemsResponse, error)
	// GetProblem returns the problem with the given ID.
	GetProblem(context.Context, *QueryGetProblemRequest) (*QueryGetProblemResponse, error)
	// GetProblemByName returns the problem registered under the given unique name.
	GetProblemByName(context.Context, *QueryGetProblemByNameRequest) (*QueryGetProblemByNameResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListProblems(ctx context.Context, req *QueryListProblemsRequest) (*QueryListProblemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProblems not implemented")
}
func (*UnimplementedQueryServer) GetProblem(ctx context.Context, req *QueryGetProblemRequest) (*QueryGetProblemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblem not implemented")
}
func (*UnimplementedQueryServer) GetProblemByName(ctx context.Context, req *QueryGetProblemByNameRequest) (*QueryGetProblemByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProblemByName not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quantumchain.problems.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListProblems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListProblemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListProblems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quantumchain.problems.v1.Query/ListProblems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListProblems(ctx, req.(*QueryListProblemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProblem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProblemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProblem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quantumchain.problems.v1.Query/GetProblem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProblem(ctx, req.(*QueryGetProblemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProblemByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProblemByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProblemByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/quantumchain.problems.v1.Query/GetProblemByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProblemByName(ctx, req.(*QueryGetProblemByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "quantumchain.problems.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListProblems",
			Handler:    _Query_ListProblems_Handler,
		},
		{
			MethodName: "GetProblem",
			Handler:    _Query_GetProblem_Handler,
		},
		{
			MethodName: "GetProblemByName",
			Handler:    _Query_GetProblemByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quantumchain/problems/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListProblemsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListProblemsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListProblemsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListProblemsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListProblemsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListProblemsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Problems) > 0 {
		for iNdEx := len(m.Problems) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Problems[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetProblemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProblemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProblemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetProblemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProblemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProblemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Problem.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetProblemByNameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProblemByNameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProblemByNameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetProblemByNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProblemByNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProblemByNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Problem.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListProblemsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListProblemsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Problems) > 0 {
		for _, e := range m.Problems {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetProblemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetProblemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Problem.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetProblemByNameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetProblemByNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Problem.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListProblemsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListProblemsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListProblemsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListProblemsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListProblemsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListProblemsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Problems", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Problems = append(m.Problems, Problem{})
			if err := m.Problems[len(m.Problems)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProblemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProblemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProblemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProblemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProblemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProblemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Problem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Problem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProblemByNameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProblemByNameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProblemByNameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProblemByNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProblemByNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProblemByNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Problem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Problem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
