// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: quantumchain/problems/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProblemKind identifies the implementation strategy for a registered problem.
// Only BUILTIN is supported in the MVP; WASM is reserved for the future.
type ProblemKind int32

const (
	ProblemKind_PROBLEM_KIND_UNSPECIFIED ProblemKind = 0
	ProblemKind_PROBLEM_KIND_BUILTIN     ProblemKind = 1
)

var ProblemKind_name = map[int32]string{
	0: "PROBLEM_KIND_UNSPECIFIED",
	1: "PROBLEM_KIND_BUILTIN",
}

var ProblemKind_value = map[string]int32{
	"PROBLEM_KIND_UNSPECIFIED": 0,
	"PROBLEM_KIND_BUILTIN":     1,
}

func (x ProblemKind) String() string {
	return proto.EnumName(ProblemKind_name, int32(x))
}

func (ProblemKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4a1ec5cfef2ee68c, []int{0}
}

// Problem is the on-chain registry entry for a daqq problem.
//
// Problems are append-only: once added, the entry stays forever. Stopping
// submissions is done by flipping `enabled` to false via gov; the historical
// data remains queryable.
type Problem struct {
	// Monotonically increasing identifier assigned by the registry. Never reused.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique human-readable name (e.g. "random_circuit"). Unique across all
	// problems, including disabled ones.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Cosmos module that implements this problem (e.g. "random_circuit").
	ModuleName string `protobuf:"bytes,3,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	// Implementation strategy. BUILTIN for the MVP.
	Kind ProblemKind `protobuf:"varint,4,opt,name=kind,proto3,enum=quantumchain.problems.v1.ProblemKind" json:"kind,omitempty"`
	// Whether new submissions are accepted. Disabled problems still serve reads.
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Beacon round in which this problem became selectable.
	AddedAtRound uint64 `protobuf:"varint,6,opt,name=added_at_round,json=addedAtRound,proto3" json:"added_at_round,omitempty"`
	// Short human-readable summary.
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *Problem) Reset()         { *m = Problem{} }
func (m *Problem) String() string { return proto.CompactTextString(m) }
func (*Problem) ProtoMessage()    {}
func (*Problem) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1ec5cfef2ee68c, []int{0}
}
func (m *Problem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Problem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Problem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Problem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Problem.Merge(m, src)
}
func (m *Problem) XXX_Size() int {
	return m.Size()
}
func (m *Problem) XXX_DiscardUnknown() {
	xxx_messageInfo_Problem.DiscardUnknown(m)
}

var xxx_messageInfo_Problem proto.InternalMessageInfo

func (m *Problem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Problem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Problem) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *Problem) GetKind() ProblemKind {
	if m != nil {
		return m.Kind
	}
	return ProblemKind_PROBLEM_KIND_UNSPECIFIED
}

func (m *Problem) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Problem) GetAddedAtRound() uint64 {
	if m != nil {
		return m.AddedAtRound
	}
	return 0
}

func (m *Problem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("quantumchain.problems.v1.ProblemKind", ProblemKind_name, ProblemKind_value)
	proto.RegisterType((*Problem)(nil), "quantumchain.problems.v1.Problem")
}

func init() {
	proto.RegisterFile("quantumchain/problems/v1/types.proto", fileDescriptor_4a1ec5cfef2ee68c)
}

var fileDescriptor_4a1ec5cfef2ee68c = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xb1, 0x4f, 0xc2, 0x40,
	0x14, 0xc6, 0x7b, 0x58, 0x41, 0x1f, 0x86, 0x90, 0x8b, 0xc3, 0x0d, 0xe6, 0x6c, 0x0c, 0x26, 0x8d,
	0x89, 0x25, 0xe8, 0xa2, 0xa3, 0x48, 0x4d, 0x1a, 0xb0, 0x92, 0x2a, 0x8b, 0x4b, 0x53, 0xb8, 0x4b,
	0xbc, 0x48, 0xaf, 0xb5, 0x5c, 0x89, 0xfe, 0x17, 0xfe, 0x59, 0x8e, 0x8c, 0x8e, 0x06, 0x46, 0xff,
	0x09, 0xc3, 0x01, 0xb1, 0x0e, 0x6e, 0xf7, 0xbe, 0xef, 0xbb, 0x7c, 0xef, 0xe5, 0x07, 0x8d, 0x97,
	0x3c, 0x92, 0x2a, 0x8f, 0x47, 0x4f, 0x91, 0x90, 0xcd, 0x34, 0x4b, 0x86, 0x63, 0x1e, 0x4f, 0x9a,
	0xd3, 0x56, 0x53, 0xbd, 0xa5, 0x7c, 0xe2, 0xa4, 0x59, 0xa2, 0x12, 0x4c, 0x8a, 0x29, 0x67, 0x93,
	0x72, 0xa6, 0xad, 0xa3, 0x6f, 0x04, 0x95, 0xfe, 0x6a, 0xc6, 0x35, 0x28, 0x09, 0x46, 0x90, 0x85,
	0x6c, 0x33, 0x28, 0x09, 0x86, 0x31, 0x98, 0x32, 0x8a, 0x39, 0x29, 0x59, 0xc8, 0xde, 0x0d, 0xf4,
	0x1b, 0x1f, 0x42, 0x35, 0x4e, 0x58, 0x3e, 0xe6, 0xa1, 0xb6, 0xb6, 0xb4, 0x05, 0x2b, 0xc9, 0x5f,
	0x06, 0x2e, 0xc1, 0x7c, 0x16, 0x92, 0x11, 0xd3, 0x42, 0x76, 0xed, 0xec, 0xd8, 0xf9, 0xaf, 0xd9,
	0x59, 0xb7, 0x76, 0x85, 0x64, 0x81, 0xfe, 0x82, 0x09, 0x54, 0xb8, 0x8c, 0x86, 0x63, 0xce, 0xc8,
	0xb6, 0x85, 0xec, 0x9d, 0x60, 0x33, 0xe2, 0x06, 0xd4, 0x22, 0xc6, 0x38, 0x0b, 0x23, 0x15, 0x66,
	0x49, 0x2e, 0x19, 0x29, 0xeb, 0x2d, 0xf7, 0xb4, 0x7a, 0xa5, 0x82, 0xa5, 0x86, 0x2d, 0xa8, 0x32,
	0x3e, 0x19, 0x65, 0x22, 0x55, 0x22, 0x91, 0xa4, 0xa2, 0x77, 0x2b, 0x4a, 0x27, 0x2e, 0x54, 0x0b,
	0xb5, 0xf8, 0x00, 0x48, 0x3f, 0xb8, 0x6b, 0xf7, 0xdc, 0xdb, 0xb0, 0xeb, 0xf9, 0x9d, 0x70, 0xe0,
	0xdf, 0xf7, 0xdd, 0x6b, 0xef, 0xc6, 0x73, 0x3b, 0x75, 0x03, 0x13, 0xd8, 0xff, 0xe3, 0xb6, 0x07,
	0x5e, 0xef, 0xc1, 0xf3, 0xeb, 0xa8, 0x7d, 0xf1, 0x31, 0xa7, 0x68, 0x36, 0xa7, 0xe8, 0x6b, 0x4e,
	0xd1, 0xfb, 0x82, 0x1a, 0xb3, 0x05, 0x35, 0x3e, 0x17, 0xd4, 0x78, 0xa4, 0xeb, 0x73, 0x4f, 0x57,
	0x3c, 0x5e, 0x7f, 0x89, 0x68, 0x1c, 0xc3, 0xb2, 0xe6, 0x71, 0xfe, 0x13, 0x00, 0x00, 0xff, 0xff,
	0xfc, 0x73, 0xaa, 0xcc, 0xb7, 0x01, 0x00, 0x00,
}

func (m *Problem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Problem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Problem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x3a
	}
	if m.AddedAtRound != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AddedAtRound))
		i--
		dAtA[i] = 0x30
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Kind != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ModuleName) > 0 {
		i -= len(m.ModuleName)
		copy(dAtA[i:], m.ModuleName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ModuleName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Problem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ModuleName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Kind != 0 {
		n += 1 + sovTypes(uint64(m.Kind))
	}
	if m.Enabled {
		n += 2
	}
	if m.AddedAtRound != 0 {
		n += 1 + sovTypes(uint64(m.AddedAtRound))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Problem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Problem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Problem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ModuleName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			m.Kind = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Kind |= ProblemKind(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedAtRound", wireType)
			}
			m.AddedAtRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AddedAtRound |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
