// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: quantumchain/random_circuit/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Distribution carries the theoretical (case A) probability distribution
// produced by a participant solving a random-circuit problem.
//
// It is a list of (state, probability) entries: each `state` is a
// computational-basis state (e.g. "00101") and each `probability` is encoded as
// a fixed-point decimal string. String encoding keeps the canonical proto
// representation deterministic across SDKs and avoids floating-point round-off
// in consensus. Entries are sorted by `state` so that independent participants
// produce a byte-identical message for the same circuit.
//
// NOTE: this is a `repeated` list rather than a proto `map` on purpose — the
// Cosmos SDK tx codec does not support map fields inside signed messages
// ("maps are not supported"), so a Msg payload must avoid them.
//
// TODO: When the `random_circuit_sampling` module is introduced for case B,
// it will use its own payload type (e.g. ShotCounts) rather than reusing this
// Distribution message.
type Distribution struct {
	Entries []ProbabilityEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
}

func (m *Distribution) Reset()         { *m = Distribution{} }
func (m *Distribution) String() string { return proto.CompactTextString(m) }
func (*Distribution) ProtoMessage()    {}
func (*Distribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_d229a02ff6455b85, []int{0}
}
func (m *Distribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Distribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Distribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Distribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distribution.Merge(m, src)
}
func (m *Distribution) XXX_Size() int {
	return m.Size()
}
func (m *Distribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Distribution.DiscardUnknown(m)
}

var xxx_messageInfo_Distribution proto.InternalMessageInfo

func (m *Distribution) GetEntries() []ProbabilityEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

// ProbabilityEntry is one (basis state -> probability) pair of a Distribution.
type ProbabilityEntry struct {
	State       string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Probability string `protobuf:"bytes,2,opt,name=probability,proto3" json:"probability,omitempty"`
}

func (m *ProbabilityEntry) Reset()         { *m = ProbabilityEntry{} }
func (m *ProbabilityEntry) String() string { return proto.CompactTextString(m) }
func (*ProbabilityEntry) ProtoMessage()    {}
func (*ProbabilityEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d229a02ff6455b85, []int{1}
}
func (m *ProbabilityEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProbabilityEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProbabilityEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProbabilityEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbabilityEntry.Merge(m, src)
}
func (m *ProbabilityEntry) XXX_Size() int {
	return m.Size()
}
func (m *ProbabilityEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbabilityEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ProbabilityEntry proto.InternalMessageInfo

func (m *ProbabilityEntry) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProbabilityEntry) GetProbability() string {
	if m != nil {
		return m.Probability
	}
	return ""
}

type ResultData struct {
	Address      string       `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Distribution Distribution `protobuf:"bytes,2,opt,name=distribution,proto3" json:"distribution"`
	SubmittedAt  time.Time    `protobuf:"bytes,3,opt,name=submitted_at,json=submittedAt,proto3,stdtime" json:"submitted_at"`
	BlockHeight  int64        `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *ResultData) Reset()         { *m = ResultData{} }
func (m *ResultData) String() string { return proto.CompactTextString(m) }
func (*ResultData) ProtoMessage()    {}
func (*ResultData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d229a02ff6455b85, []int{2}
}
func (m *ResultData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResultData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResultData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResultData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultData.Merge(m, src)
}
func (m *ResultData) XXX_Size() int {
	return m.Size()
}
func (m *ResultData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultData.DiscardUnknown(m)
}

var xxx_messageInfo_ResultData proto.InternalMessageInfo

func (m *ResultData) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ResultData) GetDistribution() Distribution {
	if m != nil {
		return m.Distribution
	}
	return Distribution{}
}

func (m *ResultData) GetSubmittedAt() time.Time {
	if m != nil {
		return m.SubmittedAt
	}
	return time.Time{}
}

func (m *ResultData) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*Distribution)(nil), "quantumchain.random_circuit.v1.Distribution")
	proto.RegisterType((*ProbabilityEntry)(nil), "quantumchain.random_circuit.v1.ProbabilityEntry")
	proto.RegisterType((*ResultData)(nil), "quantumchain.random_circuit.v1.ResultData")
}

func init() {
	proto.RegisterFile("quantumchain/random_circuit/v1/types.proto", fileDescriptor_d229a02ff6455b85)
}

var fileDescriptor_d229a02ff6455b85 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xb1, 0xae, 0xd3, 0x30,
	0x14, 0x86, 0x63, 0x5a, 0x28, 0x38, 0x19, 0x90, 0xd5, 0x21, 0xea, 0x90, 0x86, 0x8a, 0xa1, 0x42,
	0xe0, 0xd0, 0xb2, 0x23, 0x51, 0x15, 0x81, 0x98, 0xaa, 0x08, 0x31, 0xb0, 0x14, 0x27, 0x31, 0xa9,
	0x45, 0x12, 0x07, 0xfb, 0xa4, 0xa2, 0x6f, 0xd1, 0xc7, 0xea, 0xd8, 0x91, 0x09, 0x50, 0xbb, 0xf1,
	0x14, 0xa8, 0x4e, 0xc3, 0x4d, 0x3b, 0xdc, 0xbb, 0xf9, 0x1c, 0xff, 0xe7, 0xb3, 0xff, 0x5f, 0x07,
	0x3f, 0xfb, 0x5e, 0xb1, 0x02, 0xaa, 0x3c, 0x5e, 0x31, 0x51, 0x04, 0x8a, 0x15, 0x89, 0xcc, 0x97,
	0xb1, 0x50, 0x71, 0x25, 0x20, 0x58, 0x4f, 0x02, 0xd8, 0x94, 0x5c, 0xd3, 0x52, 0x49, 0x90, 0xc4,
	0x6b, 0x6b, 0xe9, 0xa5, 0x96, 0xae, 0x27, 0x83, 0x7e, 0x2a, 0x53, 0x69, 0xa4, 0xc1, 0xe9, 0x54,
	0x4f, 0x0d, 0x86, 0xa9, 0x94, 0x69, 0xc6, 0x03, 0x53, 0x45, 0xd5, 0xd7, 0x00, 0x44, 0xce, 0x35,
	0xb0, 0xbc, 0xac, 0x05, 0xa3, 0x2f, 0xd8, 0x99, 0x0b, 0x0d, 0x4a, 0x44, 0x15, 0x08, 0x59, 0x90,
	0x05, 0xee, 0xf1, 0x02, 0x94, 0xe0, 0xda, 0x45, 0x7e, 0x67, 0x6c, 0x4f, 0x5f, 0xd2, 0xdb, 0x1f,
	0xa6, 0x0b, 0x25, 0x23, 0x16, 0x89, 0x4c, 0xc0, 0xe6, 0x6d, 0x01, 0x6a, 0x33, 0xeb, 0xee, 0x7e,
	0x0d, 0xad, 0xb0, 0xc1, 0x8c, 0x3e, 0xe0, 0xc7, 0xd7, 0x12, 0xd2, 0xc7, 0xf7, 0x35, 0x30, 0xe0,
	0x2e, 0xf2, 0xd1, 0xf8, 0x51, 0x58, 0x17, 0xc4, 0xc7, 0x76, 0x79, 0xa3, 0x74, 0xef, 0x99, 0xbb,
	0x76, 0x6b, 0xf4, 0x17, 0x61, 0x1c, 0x72, 0x5d, 0x65, 0x30, 0x67, 0xc0, 0x88, 0x8b, 0x7b, 0x2c,
	0x49, 0x14, 0xd7, 0xfa, 0x0c, 0x6a, 0x4a, 0xf2, 0x09, 0x3b, 0x49, 0xcb, 0x96, 0x61, 0xd9, 0xd3,
	0xe7, 0x77, 0x79, 0x69, 0x47, 0x71, 0xf6, 0x71, 0xc1, 0x21, 0xef, 0xb0, 0xa3, 0xab, 0x28, 0x17,
	0x00, 0x3c, 0x59, 0x32, 0x70, 0x3b, 0x86, 0x3b, 0xa0, 0x75, 0xcc, 0xb4, 0x89, 0x99, 0x7e, 0x6c,
	0x62, 0x9e, 0x3d, 0x3c, 0x51, 0xb6, 0xbf, 0x87, 0x28, 0xb4, 0xff, 0x4f, 0xbe, 0x01, 0xf2, 0x04,
	0x3b, 0x51, 0x26, 0xe3, 0x6f, 0xcb, 0x15, 0x17, 0xe9, 0x0a, 0xdc, 0xae, 0x8f, 0xc6, 0x9d, 0xd0,
	0x36, 0xbd, 0xf7, 0xa6, 0x35, 0x7b, 0xbd, 0x3b, 0x78, 0x68, 0x7f, 0xf0, 0xd0, 0x9f, 0x83, 0x87,
	0xb6, 0x47, 0xcf, 0xda, 0x1f, 0x3d, 0xeb, 0xe7, 0xd1, 0xb3, 0x3e, 0x3f, 0x3d, 0xdb, 0x78, 0x51,
	0x2f, 0xce, 0x8f, 0xeb, 0xd5, 0x31, 0x7b, 0x13, 0x3d, 0x30, 0xbf, 0x79, 0xf5, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0xbf, 0xed, 0x64, 0xdb, 0x66, 0x02, 0x00, 0x00,
}

func (m *Distribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Distribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Distribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ProbabilityEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProbabilityEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProbabilityEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Probability) > 0 {
		i -= len(m.Probability)
		copy(dAtA[i:], m.Probability)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Probability)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResultData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResultData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResultData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x20
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.SubmittedAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SubmittedAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTypes(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Distribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Distribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *ProbabilityEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Probability)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *ResultData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Distribution.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.SubmittedAt)
	n += 1 + l + sovTypes(uint64(l))
	if m.BlockHeight != 0 {
		n += 1 + sovTypes(uint64(m.BlockHeight))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Distribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Distribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Distribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, ProbabilityEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProbabilityEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProbabilityEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProbabilityEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Probability", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Probability = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResultData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResultData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResultData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Distribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmittedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.SubmittedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
